# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install flutter
        run: git clone https://github.com/flutter/flutter.git
    
      - name: Set path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Switch to stable flutter channel
        run: flutter channel stable

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: build web project
        run: flutter build web
        
      - name: upload build artifact
        uses: actions/upload-artifact@master
        with:
          path: build/web

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
#      - name: Analyze project source
#        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
#      - name: Run tests
#        run: dart test
  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          path: build/web
          
#       - name: Change owner to install firebase tools
#         run: sudo chown -R 65534:121 "/root/.npm"

      - name: install npm
        shell: bash
        run: sudo apt-get install nodejs npm
        
      - name: firebase tools installation using npm
        shell: bash
        run: sudo npm install -g firebase-tools  
         
        
#       - name: choose project
#         run: firebase --project="flutter-ci-cd" --token 1//0gRHMFIbTsWtrCgYIARAAGBASNwF-L9IrOfIsIXcrD_zak4rbcnEEjWTbbR_Udh4t-DXGbc5Z1R41vBvg8r2iWZ3Oo9TPFbeizzU
        
      - name: deploy on firebase
        run: firebase deploy --only hosting --project="flutter-ci-cd-4693a" --token 1//0gttNfCEkRzITCgYIARAAGBASNwF-L9Ir73vjYB7wnErX_o5JTDUEt_lrGq-GKGAXXqhc9szMIbYCEtQKDZ-b4fQ9lR57Jt6QBvU
